jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install server deps
        working-directory: apps/server
        run: npm ci

      - name: Build server
        working-directory: apps/server
        run: npm run build

      - name: Install web deps
        working-directory: apps/web
        run: npm ci

      - name: Build web
        working-directory: apps/web
        run: npm run build
