name: release
on:
  push:
    tags: ["v*.*.*"]  # e.g. v0.1.2

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed for GHCR
    env:
      IMAGE_NAME_DH: ${{ secrets.DOCKERHUB_USER }}/eddy-llm-workbench

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU (multi-arch emulation)
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version (strip leading v)
        id: ver
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Lowercase owner for GHCR
        id: owner
        run: echo "LC_OWNER=$(echo '${GITHUB_REPOSITORY_OWNER}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Optional: add labels/annotations from git metadata
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME_DH }}
            ghcr.io/${{ steps.owner.outputs.LC_OWNER }}/eddy-llm-workbench
          tags: |
            type=raw,value=${{ steps.ver.outputs.VERSION }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=LLM Workbench
            org.opencontainers.image.description=Self-hosted web + API switchboard for multiple LLM providers (one container, zero telemetry, BYO keys).
            org.opencontainers.image.vendor=${{ steps.owner.outputs.LC_OWNER }}
            org.opencontainers.image.version=${{ steps.ver.outputs.VERSION }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & push multi-arch
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          # Push to both registries with two tags each (version + latest)
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.IMAGE_NAME_DH }}:buildcache
            type=registry,ref=ghcr.io/${{ steps.owner.outputs.LC_OWNER }}/eddy-llm-workbench:buildcache
          cache-to: |
            type=registry,ref=${{ env.IMAGE_NAME_DH }}:buildcache,mode=max
            type=registry,ref=ghcr.io/${{ steps.owner.outputs.LC_OWNER }}/eddy-llm-workbench:buildcache,mode=max
