name: release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME_DH: ${{ secrets.DOCKERHUB_USER }}/eddy-llm-workbench
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: ver
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build & push (Docker Hub only)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME_DH }}:${{ steps.ver.outputs.VERSION }}
            ${{ env.IMAGE_NAME_DH }}:latest

